name: frogsquash
adopt-info: frogsquash-source
summary: Interactive stories where you can customize characters, texts and sounds!
base: core22
architectures:
- amd64
confinement: strict
grade: stable
issues: https://github.com/kenvandine/frogsquash-snap/issues
contact: https://endlessstudios.com/
license: Proprietary

apps:
  frogsquash:
    desktop: com.endlessnetwork.frogsquash.desktop
    extensions: [gnome]
    command: FrogSquash.x86_64
    plugs:
      - audio-playback
      - joystick
      - network

parts:
  frogsquash:
    source: https://github.com/endless-network/FrogSquash_Binary/releases/download/v1.2/FrogSquash.zip
    plugin: dump
    override-prime: |
      craftctl default
      chmod +x $CRAFT_PRIME/FrogSquash.x86_64
  frogsquash-source:
    source: https://github.com/endless-network/FrogSquash_Binary/archive/refs/tags/v1.2.tar.gz
    plugin: dump
    parse-info: [com.endlessnetwork.frogsquash.appdata.xml]
    override-pull: |
      craftctl default
      sed -i 's|Icon=com.endlessnetwork.frogsquash$|Icon=${SNAP}/meta/gui/icon.png|g' $CRAFT_PART_SRC/com.endlessnetwork.frogsquash.desktop
      sed -i 's|Exec=com.endlessnetwork.frogsquash.sh$|Exec=frogsquash|g' $CRAFT_PART_SRC/com.endlessnetwork.frogsquash.desktop
      sed -i 's|version="1.1|version="1.2|g' $CRAFT_PART_SRC/com.endlessnetwork.frogsquash.appdata.xml

      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp com.endlessnetwork.FrogSquash.png $CRAFT_PART_INSTALL/meta/gui/icon.png
